[workspace]
members = ["src/scheduler", "src/backdoor"]
resolver = "2"

[package]
name = "HES"
version = "0.1.0"
edition = "2024"

[dependencies]
scheduler = { path = "src/scheduler" }
backdoor = { path = "src/backdoor" }

tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["fmt", "env-filter"] }

[workspace.dependencies]
scheduler = { path = "src/scheduler" }
backdoor = { path = "src/backdoor" }

tracing = "0.1"

[lints.clippy]
unwrap_used = "deny"
