[workspace]
members = ["src/scheduler", "src/backdoor", "src/common"]
resolver = "2"

[package]
name = "HES"
version = "0.1.0"
edition = "2024"

[dependencies]
scheduler = { path = "src/scheduler" }
backdoor = { path = "src/backdoor" }
common = { path = "src/common" }

tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["fmt", "env-filter"] }
tokio = { version = "1.47", features = ["full"] }

[workspace.dependencies]
scheduler = { path = "src/scheduler" }
backdoor = { path = "src/backdoor" }
common = { path = "src/common" }

tracing = "0.1"
tokio-cron-scheduler = "0.14"
thiserror = "2.0"

[lints.clippy]
unwrap_used = "deny"
