services:
  app:
    build: .
    container_name: headend_app
    ports:
      - "6464:6464"
      - "6565:6565"
    depends_on:
      prometheus
      postgres
    environment:
      - DATABASE_URL=postgres://postgres:password@postgres:5432/hes

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./metrics/prometheus.yml:/etc/prometheus/prometheus.yml

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "6969:3000"
    volumes:
      - grafana_data:/var/lib/grafana
    depends_on:
      - prometheus

  postgres:
    image: postgres:latest
    container_name: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: hes
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  grafana_data:
  postgres_data:
