[package]
name = "scheduler"
version = "0.1.0"
edition = "2024"

[dependencies]
common.workspace = true
metrics.workspace = true

tracing.workspace = true
tokio-cron-scheduler.workspace = true
thiserror.workspace = true
chrono.workspace = true
uuid.workspace = true

[lib]
path = "./mod.rs"

[lints.clippy]
unwrap_used = "deny"
