[package]
name = "registry_mock"
version = "0.1.0"
edition = "2024"

[[bin]]
name = "registry_mock"
path = "main.rs"

[dependencies]
common.workspace = true
clap.workspace = true
tokio.workspace = true
tracing.workspace = true
tracing-subscriber.workspace = true
thiserror.workspace = true
tokio-util.workspace = true
futures-util.workspace = true
bytes.workspace = true
futures.workspace = true
rand.workspace = true
hex.workspace = true
