backdoor:
  ip: "0.0.0.0"
  port: "6565"
metrics:
  enabled: false
scheduler:
  buckets_number: 48
database:
  type: postgres
  postgres:
    user: postgres
    password: HeadEndSystem
    url: "100.86.94.38"
    port: "5432"
cluster:
  enabled: true
  ip: "0.0.0.0"
  port: 6570
  seeds: "100.86.94.38:6570"
