backdoor:
  ip: "0.0.0.0"
  port: "6566"
metrics:
  enabled: false
scheduler:
  buckets_number: 48
database:
  type: postgres
  postgres:
    user: postgres
    password: HeadEndSystem
    url: "100.86.94.38"
    port: "5432"
cluster:
  enabled: true
  node_name: node-3
  ip: "0.0.0.0"
  port: 6571
  seeds: "100.86.94.38:6570"
