node_id: 439e82a8-7fe6-44b2-9c89-ea51c285d211
backdoor:
  ip: 0.0.0.0
  port: '6566'
metrics:
  enabled: true
  ip: 0.0.0.0
  port: '6465'
scheduler:
  buckets_number: 48
database:
  type: postgres
  postgres:
    user: postgres
    password: HeadEndSystem
    url: 100.86.94.38
    port: '5432'
cluster:
  enabled: true
  node_name: node-3
  ip: 0.0.0.0
  port: 6571
  seeds: 100.86.94.38:6570
rpc:
  enabled: true
  ip: 127.0.0.1
  port: 6601
