[package]
name = "common"
version = "0.1.0"
edition = "2024"

[dependencies]
tracing.workspace = true
bytes.workspace = true
thiserror.workspace = true
tokio-util.workspace = true
uuid.workspace = true
clap.workspace = true
sqlx.workspace = true
tokio.workspace = true
async-trait.workspace = true
chrono.workspace = true
rlp.workspace = true

[lib]
path = "./mod.rs"

[lints.clippy]
unwrap_used = "deny"
