global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'headend_app'
    static_configs:
      - targets:
          - '127.0.0.1:6464'        # node-1 (server)
          - '100.93.152.61:6464'    # node-2 (lucas)
          - '100.122.28.56:6464'    # node-2 (gonza)
          - '100.122.28.56:6465'    # node-3 (gonza)
